# Generated by Django 5.1.4 on 2024-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=500)),
                ('senha', models.IntegerField(default=0)),
            ],
        ),
    ]
