# Generated by Django 5.1.4 on 2024-12-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
    ]
