# Generated by Django 5.1.4 on 2024-12-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_engine', '0003_usuarios_nome_site_alter_usuarios_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('quando', models.CharField(default='', max_length=500, primary_key=True, serialize=False)),
                ('criador', models.CharField(default='', max_length=500)),
                ('participantes', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='', max_length=500)),
                ('local', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
