# Generated by Django 5.1.4 on 2024-12-31 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_engine', '0004_listas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listas',
            name='participantes',
        ),
        migrations.CreateModel(
            name='Participacoes',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('lista_relacionada', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='', max_length=500)),
                ('participante', models.OneToOneField(default='', max_length=500, on_delete=django.db.models.deletion.CASCADE, to='api_engine.usuarios')),
            ],
        ),
    ]
