# Generated by Django 5.1.4 on 2024-12-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_engine', '0005_remove_listas_participantes_participacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacoes',
            name='participante',
            field=models.CharField(default='', max_length=500),
        ),
    ]
