# Generated by Django 5.1.4 on 2025-01-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_engine', '0006_alter_participacoes_participante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacoes',
            name='id',
        ),
        migrations.AlterField(
            model_name='participacoes',
            name='participante',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
    ]
