# Generated by Django 5.1.4 on 2025-01-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_engine', '0007_remove_participacoes_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listas',
            name='qtd_participantes',
            field=models.IntegerField(default=0),
        ),
    ]
